### PR TITLE
Showing namespace

### PR DESCRIPTION
**Pull request by konradzdunczyk**
Move show and hide functions from globalscope to WhisperShowing namespace

### CODE REVIEW

**Comment by dominik-hadl** [comment]
This would be really great to merge ASAP.

**Comment by onmyway133** [comment]
@konrado0905 @nickskull what is the motivation behind this? For now you can just call `show` or `Whisper.show`

**Comment by konradzdunczyk** [comment]
using show/hide without namespace cause buildbreak in our CI. IMO namespace for this functions should be explicit.

**Comment by dominik-hadl** [comment]
@onmyway133 Also, for some reason the global functions are not available at all. Neither `show` nor `Whisper.show` is available when installing Whisper through carthage. Same as issue #110.

**Comment by onmyway133** [comment]
@nickskull can you try with 3.1.1? The target membership is fixed

**Comment by dominik-hadl** [comment]
@onmyway133 Ok, works now. Thanks for fixing it! 

Still don't like the idea of global functions very much though. Namespace should be explicit.

**Comment by RamonGilabert** [comment]
In Swift 3, and in the new branch, you "have" to use Whisper.show in order for the application to know what it's doing. I believe this fixes then this issue.

Make sure to check out the `swift-3` branch! :)

**Pull request closed without merging**
