### PR TITLE
Computes Shout's height dynamically

### PR DESCRIPTION
**Pull request by LucidityDesign**
For some reason it doesn't work on the first time. Can somebody help me out with that, please?

### CODE REVIEW

**Comment by LucidityDesign** [comment]
How's the status? I fixed the bug where the height was wrong the first time

**Comment by katunch** [comment]
would be nice if this PR can be merged an published

**Comment by LucidityDesign** [comment]
Are you considering to pull this request?

Can you please fix the error in the tests:
`Error: carthage-0.11 already installed`

**Comment by LucidityDesign** [comment]
Seems like df4be98016b01241123f0397728435a35e6a733f is taking care of that problem

**Pull request closed without merging**
