### PR TITLE
Fix view controller index typecast error

### LINKED ISSUE #59: Build fails on Xcode 7.3 beta 2
just a heads up, Whisper fails compilation on Xcode 7.3 beta 2.

```
ExampleApp/Pods/Whisper/Source/WhisperFactory.swift:289:72: error: value of type 'Index' (aka 'Int') has no member 'value'
        performControllerMove(navigationController.viewControllers[Int(index.value) - 1])
```

### PR DESCRIPTION
**Pull request by andreyz**
Fixes #59

### CODE REVIEW

**Comment by benwu7** [comment]
+1

**Comment by sibljon** [comment]
Let's get this :ship:ed

**Comment by ishaq** [comment]
+1 now that Xcode 7.3 is in beta 5, this needs to be shipped.

**Comment by RamonGilabert** [comment]
Awesome! Sorry for the delay, crazy days at the office:)

**Comment by andreyz** [comment]
:boom:

**Pull request merged**
