### PR TITLE
Made Message font configurable publicly

### PR DESCRIPTION
**Pull request by deepumukundan**
Message font was hardcoded to HelveticaNeue. Made the font configurable from outside as an optional parameter on Message

### CODE REVIEW

**Comment by deepumukundan** [comment]
I should have created branches for each change specifically. Let me know if you want to split this PR. I initially started with 1 change but later had to tweak few parameters for our use but are basically still API compatible for the clients of Whisper.

And thanks for making Whisper. Nicely done library!

**Comment by deepumukundan** [comment]
Closing for now as keeping this in master is obstructing further development in my side. Will create a PR later maybe after splitting features

**Comment by QuynhNguyen** [comment]
Can we make this "Made Message font configurable publicly" happen please? :(

**Comment by annca** [comment]
I would to like to be able to customize the Message font as well please.

**Pull request closed without merging**
