### PR TITLE
Add Using Whisper in Objective-C to README

### PR DESCRIPTION
**Pull request by zenangst**
Add @bcbroom's Objective-C solution to the README.

Closes https://github.com/hyperoslo/Whisper/issues/28

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Since this just explains how to do Whisper, I strongly feel that we should do a separate page in the README with just a link to it, same thing as we have in contributions. I think it makes the README a bit dirty to have it with so many lines of code, etc. When the component just needs two for each view.

But it's just an opinion.

**Comment by zenangst** [comment]
@RamonGilabert fixed :)

**Comment by RamonGilabert** [comment]
Much cleaner. Nice.

**Comment by RamonGilabert** [comment]
:fish_cake:

**Comment by zenangst** [comment]
@RamonGilabert using the wiki is a terrific idea, we should do that for all the things that have big stuffs.

**Comment by RamonGilabert** [comment]
I was actually going to suggest that. It'd be a good fit for Sugar for instance. Or Cache.

**Comment by zenangst** [comment]
unknown-19

**Pull request merged**
