### PR TITLE
Fix/shout

### PR DESCRIPTION
**Pull request by onmyway133**
- Rename free functions to lowercase first letter. This preserves Whisper namespace, and make ColorList, FontList, Config under namespace. 😈  THIS IS BREAKING CHANGES 👿 
- Allow Shout text to be 2 lines
- Update layout to deal with when Shout image is nil or subtitle is empty

simulator screen shot 13 may 2016 12 42 44
simulator screen shot 13 may 2016 13 22 42

### CODE REVIEW

**Comment by RamonGilabert** [comment]
I don't like the lowercase first letter. What do you think @zenangst? We kind of decided to go for it. Is there a reason why you do this?

**Comment by RamonGilabert** [comment]
I mean, I understand the namespace thing, but I don't like the fact that the function is lowercase, I think then the pod should be called different since Whisper just represents the first function and not the other ones.

**Comment by onmyway133** [comment]
@RamonGilabert update the screenshots, I was using a broken camera so screenshot is not correct 😁

**Comment by RamonGilabert** [comment]
Am I going to have to compile?

**Comment by zenangst** [comment]
Lets see if that fixes Travis

**Comment by zenangst** [comment]
About the whole uppercase thing, I mean to remember that we went with uppercasing because it would refer to the function existing the global scape, just like invoking a shared instance of something.

Example:

``` swift
NSFileManager.defaultManager()
```

Correct me if I'm wrong here @RamonGilabert. I still kind of like it but if it causes some issues with name spacing then I'm all for changing it.

**Comment by zenangst** [comment]
Damn you Travis!

**Comment by RamonGilabert** [comment]
We did it for that, but my point is, if the global function Whisper conflicts with the name of the pod, maybe we should change either the pod name or the function's name.

**Comment by zenangst** [comment]
@onmyway133 could you fix the merge conflicts on this one?

**Comment by onmyway133** [comment]
@zenangst It's done. Now Travis 's turn

**Comment by RamonGilabert** [comment]
Still don't agree though.

**Comment by zenangst** [comment]
For me, the optimal solution for this issue is to make a generic public API, as in, one single interface to interact with instead of having multiple.

``` swift
show(.Whisper, message: Message(title: "Bork bork bork"), to: self)
show(.Whisper, message: Message(title: "put the chocolate on the moose"), to: self)
show(.Shout, message: Announcement(title: "The Meatballs", subtitle: "Are ready!", image: UIImage(named: "meatballs"), to: self)
show(.Whistle, message: Murmur(title: "This is a small whistle..."), to: self)

hide(.Whisper)
hide(.Shout)
hide(.Whistle)
```

Something like that, what do you think?

**Comment by onmyway133** [comment]
@zenangst as long as that `.Whisper` does not steal the `Whisper` namespace, it is fine to me 😬

**Comment by zenangst** [comment]
Well it will be an `enum`, you can just drop the enum type because the function can infer it. It would actually resolve to `WhisperType`. I think that should work

**Comment by RamonGilabert** [comment]
That makes sense. Although that would mean rewriting Whisper from the ground. Which is not necessarily a bad thing?

I say rewrite because there are some things in Whisper that I'd change now because is too difficult to use or to understand what is going on.

**Pull request merged**
